# Generated by Django 4.2.5 on 2023-11-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('artist', models.CharField(max_length=250, verbose_name='Artist')),
                ('year', models.SmallIntegerField(verbose_name='Year')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('wiki_url', models.URLField(blank=True, null=True, verbose_name='Wikipedia')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
