# Generated by Django 4.2.5 on 2023-11-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('name', models.CharField(max_length=250, verbose_name='Service')),
            ],
        ),
        migrations.AddField(
            model_name='musicalbum',
            name='streams',
            field=models.ManyToManyField(related_name='albums', to='catalog.streamingservice'),
        ),
    ]
