# Generated by Django 4.2.5 on 2023-09-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicalbum',
            name='yandex_url',
            field=models.URLField(null=True, verbose_name='Yandex Music'),
        ),
        migrations.AlterField(
            model_name='musicalbum',
            name='wiki_url',
            field=models.URLField(null=True, verbose_name='Wikipedia'),
        ),
    ]
