# Generated by Django 4.2.5 on 2023-11-10 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_streamingservice_musicalbum_streams'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumStreaming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Album URL')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.musicalbum')),
                ('streaming_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.streamingservice')),
            ],
        ),
    ]
