# Generated by Django 4.2.5 on 2023-09-30 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_musicalbum_apple_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicalbum',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
